// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

loadEnv({ path: ".env.local", override: true });
loadEnv({ path: ".env", override: false });

const directUrl = process.env["DIRECT_URL"];

if (!directUrl) {
  throw new Error("DIRECT_URL e obrigatoria para operacoes Prisma CLI/migrations.");
}

const shadowDatabaseUrl = process.env["SHADOW_DATABASE_URL"];
const shadowUrl = shadowDatabaseUrl && shadowDatabaseUrl !== directUrl
  ? shadowDatabaseUrl
  : undefined;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: directUrl,
    ...(shadowUrl ? { shadowDatabaseUrl: shadowUrl } : {}),
  },
});
