#!/bin/bash
# Addendum ao staging da Sprint 1: troca o que esta staged de prisma.config.ts
# pela versao MINIMA necessaria (import bare "dotenv/config" + exigir DIRECT_URL,
# sem fallback, sem os loadEnv() extras de .env.local/.env que vieram de outra
# fonte). O arquivo de trabalho (working tree) e devolvido ao estado atual dele
# (com os loadEnv extras), como uma mudanca ainda pendente/nao commitada -
# nada e apagado, so nao entra neste commit.
set -e
cd ~/Desktop/villa-crm

echo "=== 1. Backup do prisma.config.ts atual (com os loadEnv extras) ==="
cp prisma.config.ts /tmp/prisma.config.ts.full-workingtree.bak
echo "OK"

echo ""
echo "=== 2. Escrevendo a versao MINIMA necessaria (a que sera commitada) ==="
cat > prisma.config.ts << 'EOF'
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const directUrl = process.env["DIRECT_URL"];

if (!directUrl) {
  throw new Error("DIRECT_URL e obrigatoria para operacoes Prisma CLI/migrations.");
}

const shadowUrl = process.env["SHADOW_DATABASE_URL"] && process.env["SHADOW_DATABASE_URL"] !== directUrl
  ? process.env["SHADOW_DATABASE_URL"]
  : undefined;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: directUrl,
    ...(shadowUrl ? { shadowDatabaseUrl: shadowUrl } : {}),
  },
});
EOF
echo "OK"

echo ""
echo "=== 3. Atualizando o stage (index) com a versao minima ==="
git add prisma.config.ts
echo "OK"

echo ""
echo "=== 4. Restaurando o arquivo de trabalho para o estado atual dele (com os loadEnv extras, ainda pendente/nao commitado) ==="
cp /tmp/prisma.config.ts.full-workingtree.bak prisma.config.ts
diff prisma.config.ts /tmp/prisma.config.ts.full-workingtree.bak && echo "OK: working tree restaurado, identico ao que estava antes"

echo ""
echo "=========================================="
echo "=== diff que vai para o commit (staged) de prisma.config.ts ==="
echo "=========================================="
git diff --cached -- prisma.config.ts

echo ""
echo "=========================================="
echo "=== git status completo ==="
echo "=========================================="
git status

echo ""
echo "NADA FOI COMMITADO AINDA."
